name: build-and-test-in-Docker
run-name: ${{ github.actor }} builds and tests RGL in Docker
concurrency: RGL-CI
on:
    pull_request:
        branches:
          - main
    workflow_dispatch:
        inputs:
           TAG:
             required: false
             default: latest
             type: string
permissions:
      contents: read
env:
  RGL_BUILD_TARGET: base
  TAG: ${{ inputs.TAG || 'latest' }}
  REGISTRY: ghcr.io
  PACKAGE_NAME: robotecgpulidar

defaults:
      run:
        shell: bash
jobs:
  checkout-repository:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  
  publish-env-vars-for-RGL-build:
    needs: checkout-repository
    runs-on: self-hosted
    outputs:
      RGL_BUILD_TARGET: ${{ steps.set_RGL_BUILD_TARGET.outputs.RGL_BUILD_TARGET }}
      DOCKER_IMG_URL: ${{ steps.set_DOCKER_IMG_URL.outputs.DOCKER_IMG_URL }}
    steps:
      - id: set_RGL_BUILD_TARGET
        run: echo "RGL_BUILD_TARGET=$RGL_BUILD_TARGET" >> $GITHUB_OUTPUT

      - name: Set LC repository name for docker tag
        run: |
              echo "REPOSITORY_OWNER_LC=${REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        env:
              REPOSITORY_OWNER: '${{ github.repository_owner }}'

      - id: set_DOCKER_IMG_URL
        run: echo "DOCKER_IMG_URL=${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER_LC }}/${{ env.PACKAGE_NAME }}-${{ env.RGL_BUILD_TARGET }}:${{ env.TAG }}" >> $GITHUB_OUTPUT

  build-and-test:
    needs: publish-env-vars-for-RGL-build
    uses: ./.github/workflows/build-and-test-RGL-subworkflow.yml
    with:
      RGL_BUILD_TARGET: ${{ needs.publish-env-vars-for-RGL-build.outputs.RGL_BUILD_TARGET }}
      DOCKER_IMG_URL: ${{ needs.publish-env-vars-for-RGL-build.outputs.DOCKER_IMG_URL }}
      