name: publish-Docker-image
run-name: ${{ github.actor }} publishes RGL Docker image
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      OVERRIDE_MERGE_CHECK:
       required: false
       default: true
       type: boolean
permissions:
      contents: read
env:
  RGL_BUILD_TARGET: base
  REGISTRY: ghcr.io
  PACKAGE_NAME: robotecgpulidar

defaults:
      run:
        shell: bash
jobs:
  wait_for_mutex:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-workflow-queue@v1

  checkout-repository:
    needs: wait_for_mutex
    if: github.event.pull_request.merged == true || inputs.OVERRIDE_MERGE_CHECK == true
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  # set up local Docker registry before building and pushing
  # docker run -d -p 5000:5000 --name registry registry:2.7
  build-docker-image:
    needs: checkout-repository
    runs-on: self-hosted
    steps:
      - name: Build and push Docker image to local repository
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: localhost:5000/${{ env.PACKAGE_NAME }}-${{ env.RGL_BUILD_TARGET }}:latest
          target: ${{ env.RGL_BUILD_TARGET }}

  publish-env-vars-for-testing:
    needs: build-docker-image
    runs-on: self-hosted
    outputs:
      RGL_BUILD_TARGET: ${{ steps.set_RGL_BUILD_TARGET.outputs.RGL_BUILD_TARGET }}
      DOCKER_IMG_URL: ${{ steps.set_DOCKER_IMG_URL.outputs.DOCKER_IMG_URL }}
    steps:
      - id: set_RGL_BUILD_TARGET
        run: echo "RGL_BUILD_TARGET=$RGL_BUILD_TARGET" >> $GITHUB_OUTPUT

      - id: set_DOCKER_IMG_URL
        run: echo "DOCKER_IMG_URL=localhost:5000/${{ env.PACKAGE_NAME }}-${{ env.RGL_BUILD_TARGET }}:latest" >> $GITHUB_ENV

  test-new-image:
    needs: publish-env-vars-for-testing
    uses: ./.github/workflows/build-and-test-RGL-subworkflow.yml
    with:
      RGL_BUILD_TARGET: ${{ needs.publish-env-vars-for-testing.outputs.RGL_BUILD_TARGET }}
      DOCKER_IMG_URL: ${{ needs.publish-env-vars-for-testing.outputs.DOCKER_IMG_URL }}

  publish-to-latest:
    needs: test-new-image
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set LC repository owner name for docker tag
        run: |
              echo "REPOSITORY_OWNER_LC=${REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        env:
              REPOSITORY_OWNER: '${{ github.repository_owner }}'

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to latest
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER_LC }}/${{ env.PACKAGE_NAME }}-${{ env.RGL_BUILD_TARGET }}:latest
          target: ${{ env.RGL_BUILD_TARGET }}