name: publish-docker-image
run-name: ${{ github.actor }} publishes RGL Docker image
on: [push, workflow_dispatch]
concurrency: RGL-CI
permissions:
      contents: read
env:
  RGL_BUILD_TARGET: base
  REGISTRY: ghcr.io

defaults:
      run:
        shell: bash
jobs:
  checkout-repository:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

  build-docker-image:
    needs: checkout-repository
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set LC repository owner name for docker tag
        run: |
              echo "REPOSITORY_OWNER_LC=${REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        env:
              REPOSITORY_OWNER: '${{ github.repository_owner }}'

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to latest
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER_LC }}/${{ env.RGL_BUILD_TARGET }}:latest
          target: ${{ env.RGL_BUILD_TARGET }}

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build and push Docker image to branch name tag
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER_LC }}/${{ env.RGL_BUILD_TARGET }}:${{ steps.extract_branch.outputs.branch }}
          target: ${{ env.RGL_BUILD_TARGET }}