name: test-all-configurations
run-name: ${{ github.actor }} builds and tests RGL in docker
on: [workflow_dispatch, push]
concurrency: RGL-CI
permissions:
      contents: read
jobs:
  test-all-configurations:
    runs-on: self-hosted
    steps:
      - name: test base
        uses: ./.github/workflows/build-RGL-and-test.yml@main
        with:
            RGL_BUILD_TARGET: base
    #   - name: test with-pcl
    #     uses: ./.github/workflows/build-RGL-and-test.yml@main
    #     with:
    #         RGL_BUILD_TARGET: with-pcl
      - name: test with-ros2
        uses: ./.github/workflows/build-RGL-and-test.yml@main
        with:
            RGL_BUILD_TARGET: with-ros2
    #   - name: test with-pcl-and-ros2
    #     uses: ./.github/workflows/build-RGL-and-test.yml@main
    #     with:
    #         RGL_BUILD_TARGET: with-pcl-and-ros2
      